### ISSUE TITLE
I hava a question

### ISSUE THREAD

**Issue by xiaoACE6716** [MattyHD0/minecraft-tooltip-generator#1]
Hello Matias!I'm trying to use your code, but it produces garbled characters on windows system but not on linux system, do you know how to solve this problem?
![windows](https://user-images.githubusercontent.com/94223505/219925158-8dede4f8-9eec-4afd-b237-701da3c1714c.png)
![linux](https://user-images.githubusercontent.com/94223505/219925190-f391d4fe-7ddd-48d6-82a2-785704684e21.png)

**Comment by MattyHD0** [comment]
Hi xiao, I honestly couldn't tell you what the problem is exactly since this algorithm was programmed and tested directly in Windows 10 and it has worked correctly for me, but it occurs to me that it could be something related to the encoding of files in Windows or the language from your pc (I have tested it with the Spanish language)
